export const skills = [
  { name: "React", level: 91 },
  { name: "TypeScript", level: 77 },
  { name: "JavaScript (ES6)", level: 87 },
  { name: "TailwindCSS", level: 94 },
  { name: "jQuery", level: 78 },
  { name: "Git & GitHub", level: 73 },
  { name: "SQL", level: 79 },
  { name: "Java", level: 81 },
  { name: "Hibernate", level: 75 },
  { name: "Core & Advanced Java", level: 72 },
  { name: "Spring", level: 72 },
  { name: "JDBC", level: 72 },
  { name: "Bootstrap", level: 96 },
  { name: "HTML5 & CSS3", level: 93 },
  { name: "Framer Motion", level: 77 },
];
